name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [debug,release]
        sanitizer: [""]
        include:
          - os: macos-latest
            build_type: debug
            sanitizer: "-fsanitize=address"
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Generating Makefiles
      shell: bash
      run: |
        cmake . -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_FLAGS=${{ matrix.sanitizer }}  \
          -DCMAKE_EXE_LINKER_FLAGS=${{ matrix.sanitizer }}
    - name: Compiling
      shell: bash
      run: |
        ninja
    - name: Running Tests
      shell: bash
      run: |
        msgpack/tests/Msgpack_tests
